# Generated by Django 5.0.7 on 2024-07-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_task_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Task',
        ),
    ]
